TRUNCATE TABLE payments RESTART IDENTITY CASCADE;
TRUNCATE TABLE bookings RESTART IDENTITY CASCADE;
TRUNCATE TABLE accommodation_amenities RESTART IDENTITY CASCADE;
TRUNCATE TABLE accommodations RESTART IDENTITY CASCADE;
TRUNCATE TABLE users_roles RESTART IDENTITY CASCADE;
TRUNCATE TABLE roles RESTART IDENTITY CASCADE;
TRUNCATE TABLE users RESTART IDENTITY CASCADE;